name: laurelrankin.com
favicon: null
layout_spectrum: 0.2651968626305461
typography_spectrum: 0.325986786512658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.37535206507891417
  lightness: 0.6673568601254374
  saturation: 0.30006436281837523
  rhythmicContrast: 0.33909558574669063
purpose: []
