name: laurelrankin.com
favicon: null
layout_spectrum: 0.2651968626305461
typography_spectrum: 0.325986786512658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#32aff9'
    - '#f2f8ba'
    - '#0c1117'
    - '#294f36'
    - '#53793a'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
